import { Ionicons } from '@expo/vector-icons';
import React, { useMemo, useState } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { AnimatedPressable } from '../components/AnimatedPressable';
import { colors, radii, spacing } from '../theme';
import { SectionHeader } from '../v01/PanelWidgets';
import { V02AdminPanel } from '../v02/AdminPanel';
import { V02DemoState } from '../v02/types';
import { statusLabel } from './state';
import { V03DemoState } from './types';

type Result={ok:boolean;message:string};
type OperationsProps=React.ComponentProps<typeof V02AdminPanel>;
export function V03AdminPanel({operationsProps,appointmentState,operationsState: _operationsState,onResetV03,onMessage}:{operationsProps:OperationsProps;appointmentState:V03DemoState;operationsState:V02DemoState;onResetV03:()=>Promise<Result>|Result;onMessage:(message:string,success?:boolean)=>void}){
  const[area,setArea]=useState<'appointments'|'admin'>('appointments');
  const stats=useMemo(()=>({total:appointmentState.appointments.length,active:appointmentState.appointments.filter((item)=>!['completed','cancelled','no_show'].includes(item.status)).length,completed:appointmentState.appointments.filter((item)=>item.status==='completed').length}),[appointmentState.appointments]);
  if(area==='admin')return <View style={styles.root}><Tabs area={area} onChange={setArea}/><View style={styles.fill}><V02AdminPanel {...operationsProps}/></View></View>;
  return <View style={styles.root}><Tabs area={area} onChange={setArea}/><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
    <View style={styles.hero}><View style={styles.icon}><Ionicons name="analytics" size={27} color={colors.white}/></View><View style={styles.copy}><Text style={styles.eyebrow}>ADMIN RANDEVU RAPORU</Text><Text style={styles.title}>Akış ve event merkezi</Text><Text style={styles.text}>Her durum değişikliği rol ve zaman bilgisiyle kaydedilir.</Text></View></View>
    <View style={styles.metrics}><Metric label="Toplam" value={stats.total} accent={colors.secondary}/><Metric label="Aktif" value={stats.active} accent={colors.amber}/><Metric label="Bitti" value={stats.completed} accent={colors.green}/></View>
    <SectionHeader title="Son event kayıtları" meta={`${appointmentState.appointmentEvents.length} event`}/>
    <View style={styles.list}>{appointmentState.appointmentEvents.slice(0,12).map((event)=>{const appointment=appointmentState.appointments.find((item)=>item.id===event.appointmentId);return <View key={event.id} style={styles.event}><View style={styles.eventIcon}><Ionicons name="pulse" size={18} color={colors.secondary}/></View><View style={styles.eventInfo}><Text style={styles.eventTitle}>{appointment?.code??'Randevu'} · {statusLabel(event.toStatus)}</Text><Text style={styles.eventText}>{event.actor} · {new Date(event.createdAt).toLocaleString('tr-TR')}</Text>{!!event.note&&<Text style={styles.eventNote}>{event.note}</Text>}</View></View>})}</View>
    <AnimatedPressable style={styles.reset} onPress={async()=>{const response=await onResetV03();onMessage(response.message,response.ok)}}><Ionicons name="refresh" size={18} color={colors.red}/><Text style={styles.resetText}>v0.3 randevu verilerini sıfırla</Text></AnimatedPressable>
  </ScrollView></View>;
}
function Tabs({area,onChange}:{area:'appointments'|'admin';onChange:(v:'appointments'|'admin')=>void}){return <View style={styles.tabs}><AnimatedPressable style={[styles.tab,area==='appointments'&&styles.tabActive]} onPress={()=>onChange('appointments')}><Ionicons name="calendar-outline" size={17} color={area==='appointments'?colors.white:colors.textMuted}/><Text style={[styles.tabText,area==='appointments'&&styles.tabTextActive]}>Randevu & Event</Text></AnimatedPressable><AnimatedPressable style={[styles.tab,area==='admin'&&styles.tabActive]} onPress={()=>onChange('admin')}><Ionicons name="shield-checkmark-outline" size={17} color={area==='admin'?colors.white:colors.textMuted}/><Text style={[styles.tabText,area==='admin'&&styles.tabTextActive]}>v0.1 + v0.2</Text></AnimatedPressable></View>}
function Metric({label,value,accent}:{label:string;value:number;accent:string}){return <View style={styles.metric}><Text style={[styles.metricValue,{color:accent}]}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>}
const styles=StyleSheet.create({root:{flex:1},fill:{flex:1},tabs:{flexDirection:'row',gap:6,paddingHorizontal:spacing.md,paddingBottom:8},tab:{flex:1,minHeight:44,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:6,borderRadius:15,backgroundColor:colors.card,borderWidth:1,borderColor:colors.border},tabActive:{backgroundColor:colors.surfaceElevated},tabText:{color:colors.textMuted,fontSize:10.5,fontWeight:'900'},tabTextActive:{color:colors.white},content:{paddingHorizontal:spacing.md,paddingTop:3,paddingBottom:34},hero:{minHeight:122,flexDirection:'row',alignItems:'center',gap:12,padding:15,borderRadius:24,backgroundColor:'rgba(108,99,255,0.1)',borderWidth:1,borderColor:'rgba(108,99,255,0.22)'},icon:{width:54,height:54,borderRadius:19,alignItems:'center',justifyContent:'center',backgroundColor:colors.secondary},copy:{flex:1},eyebrow:{color:colors.textMuted,fontSize:8.5,fontWeight:'900'},title:{color:colors.white,fontSize:18,fontWeight:'900',marginTop:4},text:{color:colors.textMuted,fontSize:9.5,lineHeight:14,marginTop:5},metrics:{flexDirection:'row',gap:8,marginTop:11},metric:{flex:1,minHeight:70,alignItems:'center',justifyContent:'center',borderRadius:18,backgroundColor:colors.card,borderWidth:1,borderColor:colors.border},metricValue:{fontSize:20,fontWeight:'900'},metricLabel:{color:colors.textMuted,fontSize:8.5,marginTop:3},list:{gap:8},event:{minHeight:76,flexDirection:'row',alignItems:'center',gap:10,padding:11,borderRadius:radii.lg,backgroundColor:colors.card,borderWidth:1,borderColor:colors.border},eventIcon:{width:42,height:42,borderRadius:14,alignItems:'center',justifyContent:'center',backgroundColor:'rgba(108,99,255,0.12)'},eventInfo:{flex:1,minWidth:0},eventTitle:{color:colors.white,fontSize:11,fontWeight:'900'},eventText:{color:colors.textMuted,fontSize:8.5,marginTop:3},eventNote:{color:colors.textMuted,fontSize:8.5,lineHeight:12,marginTop:4},reset:{minHeight:48,marginTop:20,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7,borderRadius:15,backgroundColor:'rgba(255,94,108,0.07)',borderWidth:1,borderColor:'rgba(255,94,108,0.2)'},resetText:{color:colors.red,fontSize:10.5,fontWeight:'900'}});
